version: '3.4'
services:
  app:
    build:
      context: .
      network: host
    volumes:
      - "/etc/watchpoint:/etc/watchpoint"
      - "/var/lib/watchpoint:/var/lib/watchpoint"
    network_mode: host
    environment:
      - WATCHPOINT_PORT=1080
